; COMPDECL.LSP -- common compiler declarations

(declare (:special special-list list-flag arg-list aux-list opt-list local-size
		    local-list rest-list code-list pcode-list asm-list special-form-list
		    self-name declare macro-list local-fcn-list default-special-form
		    local-flag target-type list-sink constant-list
	   ; functions
		    :compile :cload :ed-compile :ed-comp-asm )
)))
